version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public:ro
      - ./.env:/app/.env:ro
      - ./sessions:/app/sessions
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  argo:
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/arguments/
    # https://hub.docker.com/r/cloudflare/cloudflared/tags
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate --retries 15 --protocol http2 --overwrite-dns --hostname archivebox-pocket.zervice.io --url http://nodejs:3000 --name archivebox-pocket.zervice.io
    volumes:
      - ./etc/cloudflared:/etc/cloudflared
    cpus: 4
    mem_limit: 2048m
    restart: on-failure
